config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'home#index'

  resources :contacts, only: [:new, :create]
  resources :home do
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :detail

  def headers
    {
      :subject => "MultiPlayers Club Contact",
      :to => "msaqib52@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :gamer_tag, :platform, :presence => true

  has_and_belongs_to_many :games

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :platform, :gamer_tag, game_ids: []])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :platform, :gamer_tag, game_ids: []])
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Unable to send message, Please fill all the fields.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!, except: [:index]

  def index
    @q = User.where.not(id: current_user).ransack(params[:q])
    if params[:q] && params[:q][:platform_eq].present? && params[:q][:games_id_eq].present?
      @users = @q.result(distinct: true)
    end
  end

  def search
    index
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

  def get_column_name
    if params[:q][:platform_eq] == "xbox"
      "Gamer Tag"
    elsif params[:q][:platform_eq] == "playstation"
      "Playstation ID"
    else
      "Player ID"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/create.html.erb
<br />
<br />
<br />
<br />
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="contactHeadingGreen">
            <% flash.each do |key, value| %>
              <%= value %>
            <% end %>
          </h2>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>
      <h2>Contact Us</h2>

      <%= form_for(@contact, html: {class: "form-horizontal"}) do |f| %>

        <div class="form-group">
          <%= f.label :name, class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :detail, class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= f.text_area :detail, rows: "4", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-8">
            <%= f.submit "Send", class: "btn btn-success pull-left" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

app/views/home/index.html.erb
<br />
<br />
<br />
<br />
<br />
<br />
<div class="inner cover">
  <% if current_user %>
    <h1 class="cover-heading">Find Online Players</h1>
    <p class="lead">
      <%= search_form_for @q, url: search_home_index_path,
                        html: { method: :post,  class: "form-inline" } do |f| %>
        <div class="form-group">
          <label class="sr-only" for="platform_eq">Gaming Platform</label>
          <%= f.select :platform_eq, [['XBox','xbox'],['Playstation','playstation'],['PC','pc']], {include_blank: "Gaming Platform"}, {class: "form-control input-lg"} %>
        </div>

        <div class="form-group">
          <label class="sr-only" for="games_id_eq">Game</label>
          <%= f.select :games_id_eq, Game.all.collect {|g| [ g.name, g.id ] }, {include_blank: "Choose Video Game"}, { class: "form-control game-multiselect" } %>
        </div>
        <%= f.submit "Search", class: "btn btn-default btn-lg" %>
      <% end %>
    </p>
      <% if params[:q].present? %>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th><%= get_column_name %></th>
            <th>Platform</th>
          </tr>
        </thead>
        <tbody>
          <% if @users.present? %>
            <% @users.each.with_index(1) do |user, index| %>
              <tr>
                <th scope="row"><%= index %></th>
                <td><%= user.name %></td>
                <td><%= user.gamer_tag %></td>
                <td><%= user.platform %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <th colspan="4" style="text-align: center;">No players found, Please invite your friends to Sign up.</th>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end%>
  <% else %>
  <h1 class="cover-heading">MultiPlayers Club</h1>
  <p class="lead">MultiPlayers Club is where online video game players find each other. Sign up now and be friends with thousands of players ready to play online games.</p>
  <p class="lead">
  <%= link_to('Sign Up', new_registration_path(:user), class: "btn btn-lg btn-default")  %>
  </p>
  <% end %>
</div>

<div class="mastfoot">
  <div class="inner">
    <p>MultiPlayers Club © <%= DateTime.now.year %></p>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><strong>This form contains <%= pluralize(object.errors.count, 'error') %>.</strong></p>
      <ul style="text-align:left;">
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Find online friends for multiplayer gaming</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body cz-shortcut-listen="true">
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><%= link_to "MpC", root_path %></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <%= nav_link "Home", root_path %>
                  <%= nav_link "Contact Us", new_contact_path %>
                  <% if user_signed_in? %>
                    <%= nav_link "Profile", edit_user_registration_path %>
                    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %> </li>
                  <% else %>
                    <%= nav_link('Sign Up', new_registration_path(:user))  %>
                    <%= nav_link('Login', new_user_session_path)  %>
                  <% end %>
                </ul>
              </nav>
            </div>
          <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>